# Generated by Django 5.1.3 on 2024-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StyleHire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bridal', 'Bridal'), ('casual', 'Casual'), ('classic', 'Classic'), ('formal', 'Formal'), ('party', 'Party')], default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='female', max_length=10),
        ),
    ]
